When you combine multiple series together it is called Dataframe

In [1]:
import numpy as np 
import pandas as pd

**Creating a Dataframe**

In [11]:
#using dictionary 
data={
    'Name':['Ram','Sita','Jignu','Anshuiya'],
    'Age':[21,24,25,23],
    'Country':['India','Italy','USA','Nepal'],
    'Salary':['1lakh','2lakh','3lakh','10crore']
}

pd.DataFrame(data)

       Name  Age Country   Salary
0       Ram   21   India    1lakh
1      Sita   24   Italy    2lakh
2     Jignu   25     USA    3lakh
3  Anshuiya   23   Nepal  10crore

In [13]:
#using list
data_list=[
    ['Ram',21,'India','1lakh'],
    ['Sita',24,'Italy','2lakh'],
    ['Jignu',25,'USA','3lakh'],
    ['Anshuiya',23,'Nepal','10crore']
]
pd.DataFrame(data_list)

#in this case indexes 0 ,1 ,2 come as labels

          0   1      2        3
0       Ram  21  India    1lakh
1      Sita  24  Italy    2lakh
2     Jignu  25    USA    3lakh
3  Anshuiya  23  Nepal  10crore

In [16]:
#using list u have to manually customize labels
data_list=[
    ['Ram',21,'India','1lakh'],
    ['Sita',24,'Italy','2lakh'],
    ['Jignu',25,'USA','3lakh'],
    ['Anshuiya',23,'Nepal','10crore']
]

column_name=['Name','Age','Country','Salary']
df2=pd.DataFrame(data_list,columns=column_name)

**Selection and Indexing of Columns**

In [17]:
df2['Name']  #have to pass labels

0         Ram
1        Sita
2       Jignu
3    Anshuiya
Name: Name, dtype: object

In [18]:
df2[['Name','Country']] #for multiple have to past a list of lists

       Name Country
0       Ram   India
1      Sita   Italy
2     Jignu     USA
3  Anshuiya   Nepal

**Creating a new column**

In [28]:
df2['Designation']=['Doctor','Lawyer','Doctor','Software Development Engineer']
df2

       Name  Age Country   Salary                    Designation
0       Ram   21   India    1lakh                         Doctor
1      Sita   24   Italy    2lakh                         Lawyer
2     Jignu   25     USA    3lakh                         Doctor
3  Anshuiya   23   Nepal  10crore  Software Development Engineer

**Removing columns**

In [29]:
df2.drop('Designation',axis=1) #vertical axis =1 but thisis only dropped in copy in real data changes arent reflected

       Name  Age Country   Salary
0       Ram   21   India    1lakh
1      Sita   24   Italy    2lakh
2     Jignu   25     USA    3lakh
3  Anshuiya   23   Nepal  10crore

In [30]:
df2 #changes not reflected

       Name  Age Country   Salary                    Designation
0       Ram   21   India    1lakh                         Doctor
1      Sita   24   Italy    2lakh                         Lawyer
2     Jignu   25     USA    3lakh                         Doctor
3  Anshuiya   23   Nepal  10crore  Software Development Engineer

In [31]:
df2.drop('Designation',axis=1, inplace = True)

In [32]:
df2

       Name  Age Country   Salary
0       Ram   21   India    1lakh
1      Sita   24   Italy    2lakh
2     Jignu   25     USA    3lakh
3  Anshuiya   23   Nepal  10crore

In [34]:
#to drop multiple columns drop list 
df2.drop(['Name','Country'],axis=1)

   Age   Salary
0   21    1lakh
1   24    2lakh
2   25    3lakh
3   23  10crore

**Selecting Rows**

In [37]:
df2.loc[3] #loc means location

Name       Anshuiya
Age              23
Country       Nepal
Salary      10crore
Name: 3, dtype: object

In [40]:
df2.loc[[1,3]]

       Name  Age Country   Salary
1      Sita   24   Italy    2lakh
3  Anshuiya   23   Nepal  10crore

In [42]:
df2.iloc[3] #similar to loc iloc is index loc

Name       Anshuiya
Age              23
Country       Nepal
Salary      10crore
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [43]:
df2

       Name  Age Country   Salary
0       Ram   21   India    1lakh
1      Sita   24   Italy    2lakh
2     Jignu   25     USA    3lakh
3  Anshuiya   23   Nepal  10crore

In [48]:
df2.loc[[0,1]][['Country','Salary']]

  Country Salary
0   India  1lakh
1   Italy  2lakh

In [50]:
df2.loc[[2,3]][['Name','Age']]

       Name  Age
2     Jignu   25
3  Anshuiya   23

**Conditional Selection**

In [ ]:
#I only see those people whose age is above 21

In [52]:
df2[df2['Age']>21]

       Name  Age Country   Salary
1      Sita   24   Italy    2lakh
2     Jignu   25     USA    3lakh
3  Anshuiya   23   Nepal  10crore

In [ ]:
#I only want those people whose age is above 21 and are from Nepal cause they are extremely talented

In [57]:
df2[(df2['Age']>21) & (df2['Country']=='Nepal')]

       Name  Age Country   Salary
3  Anshuiya   23   Nepal  10crore